// Local-only QA; excluded from static site packaging. Never loaded by the app.
const frame=document.querySelector('iframe'),report=document.getElementById('report');
const run=s=>frame.contentWindow.eval(s),show=o=>report.textContent=JSON.stringify(o,null,2);
const buttons={};function button(name,fn){const b=document.createElement('button');b.textContent=name;b.onclick=async()=>{try{await fn();}catch(e){show({error:e.stack});}};document.getElementById('controls').append(b);buttons[name]=b;}
function snapshot(){return run(`({position:{x:state.x,y:state.y,z:state.z},running:state.isRunning,flying:state.isFlying,complete:state.missionCompleted,beacons:beaconsTriggered,score:currentScore,collision:!!state.collisionDetected,draw:{...renderer.info.render},memory:{...renderer.info.memory},camera:{position:camera.position.toArray(),target:{...camTarget},radius:camRadius,theta:camTheta,phi:camPhi},objects:(()=>{let meshes=0,casters=0,materials=new Set(),geometries=new Set(),lights=[];environmentGroup.traverse(o=>{if(o.isMesh){meshes++;casters+=o.castShadow?1:0;geometries.add(o.geometry.uuid);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m.uuid));}});scene.traverse(o=>{if(o.isLight)lights.push({type:o.type,intensity:o.intensity,shadow:o.castShadow})});return {meshes,casters,materials:materials.size,geometries:geometries.size,lights}})()})`);}
function view(kind){run(`resetSimulator();state.collisionDetected=false;hideAppMessage();followDrone=${kind==='takeoff'||kind==='flight'};camTheta=45;camPhi=${kind==='top'?10:kind==='overview'?35:30};camRadius=${kind==='overview'||kind==='top'?3200:kind==='objective'?500:220};state.x=${kind==='flight'?75:-675};state.z=${kind==='flight'?-225:-675};state.y=${kind==='flight'?50:0};lastSafePos={x:state.x,y:state.y,z:state.z};camTarget={x:${kind==='objective'?825:kind==='overview'||kind==='top'?0:kind==='flight'?75:-675},y:0,z:${kind==='objective'?675:kind==='overview'||kind==='top'?0:kind==='flight'?-225:-675}};updateCameraPosition();`);show(snapshot());}
frame.src='../../index.html?qa='+Date.now();frame.onload=async()=>{await frame.contentWindow.startMission(1);frame.contentWindow.closeBriefing();frame.contentWindow.document.querySelector('[data-view="world"]').click();frame.contentWindow.document.addEventListener('keydown',e=>{if(e.key==='F8')document.body.classList.toggle('capture')});view('overview');};
['overview','top','takeoff','flight','objective'].forEach(k=>button(k,()=>view(k)));
button('Status',()=>show(snapshot()));
button('Hide',()=>document.body.classList.add('capture'));
button('Measure',async()=>show(await run(`(async()=>{let a=[],p=performance.now();for(let i=0;i<121;i++)await new Promise(r=>requestAnimationFrame(t=>{a.push(t-p);p=t;r()}));a.shift();a.sort((x,y)=>x-y);return {draw:{...renderer.info.render},memory:{...renderer.info.memory},medianMs:a[60],p95Ms:a[114],width:renderer.domElement.width,height:renderer.domElement.height};})()`)));
button('Contract',()=>show(run(`(()=>{const previous={...state},safe={...lastSafePos};environmentGroup.updateMatrixWorld(true);const rays=[];currentMazeGrid.forEach((row,i)=>row.forEach((v,j)=>{if(v===1)return;state.x=mazeOffsetX+j*150+75;state.z=mazeOffsetZ+i*150+75;for(const y of [40,95,220,321]){state.y=y;for(const heading of [0,90,180,270]){state.heading=heading;for(const d of ['front','left','right'])rays.push(getSensorReading(d,'cm'));}}}));const collisions=[];state.collisionDetected=true;for(let z=-900;z<=900;z+=75)for(let x=-900;x<=900;x+=75){state.x=x;state.z=z;state.y=95;lastSafePos={x:-675,y:95,z:-675};handleWallCollision();collisions.push(state.x,state.z);}Object.assign(state,previous);lastSafePos=safe;return {grid:currentMazeGrid,spawn:spawnPosition,target:targetPosition,rays,collisions};})()`)));
async function fly(file){frame.contentWindow.resetSimulator();frame.contentWindow.ensureBlocklyWorkspaceReady();frame.contentWindow.applyBlocklyWorkspaceXmlText(await (await fetch('../../test/fixtures/'+file+'?qa='+Date.now(),{cache:'no-store'})).text());frame.contentWindow.document.getElementById('run-blockly-btn').click();show('Running');}
button('Run full',()=>fly('mission1-inspections.xml'));button('Run direct',()=>fly('mission1-direct.xml'));
button('Reset',()=>{frame.contentWindow.resetSimulator();show(snapshot())});
button('Mission 2 baseline',()=>{run(`changeScene('city');followDrone=false;camRadius=3200;camTheta=45;camPhi=35;camTarget={x:0,y:0,z:0};updateCameraPosition();`);show(run(`({grid:currentMazeGrid,spawn:spawnPosition,target:targetPosition,lights:scene.children.filter(o=>o.isLight).map(o=>[o.color.getHex(),o.intensity,o.position.toArray(),o.groundColor?.getHex()]),exposure:renderer.toneMappingExposure})`))});
button('Mission 1',()=>{run(`changeScene('tunnel')`);view('overview')});
button('Build timing',async()=>{
 const times=[];
 for(let n=0;n<5;n++) {times.push(run(`(()=>{const t=performance.now();changeScene('tunnel');return performance.now()-t})()`));await new Promise(r=>requestAnimationFrame(r));}
 show({buildMs:times,medianMs:times.slice().sort((a,b)=>a-b)[2],snapshot:snapshot()});
});
button('Run collision',()=>fly('mission1-collision.xml'));
